services:
  db:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-avp}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-avp_psw!}
      POSTGRES_DB: ${POSTGRES_DB:-avp_db}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-avp} -d ${POSTGRES_DB:-avp_db}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - avp-network

  api:
    build: .
    container_name: avp-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    networks:
      - avp-network

volumes:
  db_data:

networks:
  avp-network: